version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    container_name: elastic
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    ports:
     - "9200:9200"
    networks:
      elkm:
        aliases:
          - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    restart: always
    ports:
     - "5601:5601"
    networks:
      elkm:
        aliases:
          - kibana
    depends_on:
      - elastic
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.0.0
    container_name: metricbeat
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: always
    networks:
      elkm:
    depends_on:
      - kibana
networks:
  elkm:
